# Generated by Django 4.2.6 on 2023-10-06 12:18

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Actor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=100, verbose_name="Имя актера"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=100, verbose_name="Фамилия актера"),
                ),
                ("birthdate", models.DateField(verbose_name="Дата рождения")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Описание"),
                ),
                (
                    "picture",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="actor/images/%Y/%m/%d/",
                        verbose_name="Фото актера",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("М", "Мужчина"), ("Ж", "Женщина"), ("U", "Unknown")],
                        default="U",
                        max_length=1,
                        verbose_name="Гендер",
                    ),
                ),
            ],
            options={
                "verbose_name": "Актер",
                "verbose_name_plural": "Актеры",
                "ordering": ["last_name", "first_name"],
            },
        ),
    ]
