# Generated by Django 4.2.6 on 2023-10-09 13:58

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import movies.models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Название"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        max_length=100, unique=True, verbose_name="Идентификатор"
                    ),
                ),
            ],
            options={
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
                "ordering": ["name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Название"
                    ),
                ),
            ],
            options={
                "verbose_name": "Страна",
                "verbose_name_plural": "Страны",
                "ordering": ["name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Director",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100, verbose_name="Имя")),
                (
                    "last_name",
                    models.CharField(
                        db_index=True, max_length=100, verbose_name="Фамилия"
                    ),
                ),
                (
                    "birthdate",
                    models.DateField(
                        validators=[
                            django.core.validators.MaxValueValidator(
                                datetime.datetime(
                                    2023,
                                    10,
                                    9,
                                    13,
                                    58,
                                    6,
                                    432538,
                                    tzinfo=datetime.timezone.utc,
                                ),
                                "Дата рождения не может быть больше нынешней!",
                            )
                        ],
                        verbose_name="Дата рождения",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Описание"),
                ),
                (
                    "picture",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=movies.models.get_upload_path,
                        verbose_name="Фото",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("М", "Мужчина"), ("Ж", "Женщина"), ("U", "Unknown")],
                        default="U",
                        max_length=1,
                        verbose_name="Гендер",
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)ss",
                        to="movies.country",
                        verbose_name="Страна",
                    ),
                ),
            ],
            options={
                "verbose_name": "Режиссер",
                "verbose_name_plural": "Режиссеры",
                "ordering": ["last_name", "first_name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Название"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        max_length=100, unique=True, verbose_name="Идентификатор"
                    ),
                ),
            ],
            options={
                "verbose_name": "Жанр",
                "verbose_name_plural": "Жанры",
                "ordering": ["name"],
                "abstract": False,
            },
        ),
        migrations.AlterField(
            model_name="actor",
            name="birthdate",
            field=models.DateField(
                validators=[
                    django.core.validators.MaxValueValidator(
                        datetime.datetime(
                            2023, 10, 9, 13, 58, 6, 432538, tzinfo=datetime.timezone.utc
                        ),
                        "Дата рождения не может быть больше нынешней!",
                    )
                ],
                verbose_name="Дата рождения",
            ),
        ),
        migrations.AlterField(
            model_name="actor",
            name="first_name",
            field=models.CharField(max_length=100, verbose_name="Имя"),
        ),
        migrations.AlterField(
            model_name="actor",
            name="last_name",
            field=models.CharField(
                db_index=True, max_length=100, verbose_name="Фамилия"
            ),
        ),
        migrations.AlterField(
            model_name="actor",
            name="picture",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=movies.models.get_upload_path,
                verbose_name="Фото",
            ),
        ),
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, max_length=100, verbose_name="Название"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Описание"),
                ),
                (
                    "release_year",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MaxValueValidator(
                                2023, "Год выпуска не может быть больше нынешнего!"
                            )
                        ],
                        verbose_name="Год выпуска",
                    ),
                ),
                (
                    "poster",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="movies/%Y/%m/%d",
                        verbose_name="Постер",
                    ),
                ),
                (
                    "pub_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата публикации"
                    ),
                ),
                (
                    "actors",
                    models.ManyToManyField(
                        related_name="actor_movies",
                        to="movies.actor",
                        verbose_name="Актеры фильма",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        default="Без категории",
                        null=True,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        to="movies.category",
                    ),
                ),
                (
                    "countries",
                    models.ManyToManyField(
                        related_name="country_movies",
                        to="movies.country",
                        verbose_name="Страны производства",
                    ),
                ),
                (
                    "directors",
                    models.ManyToManyField(
                        related_name="director_movies",
                        to="movies.director",
                        verbose_name="Режиссеры фильма",
                    ),
                ),
                (
                    "genres",
                    models.ManyToManyField(
                        related_name="genre_movies",
                        to="movies.genre",
                        verbose_name="Жанры фильма",
                    ),
                ),
            ],
            options={
                "verbose_name": "Фильм",
                "verbose_name_plural": "Фильмы",
                "ordering": ["name", "release_year"],
            },
        ),
        migrations.AddField(
            model_name="actor",
            name="country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)ss",
                to="movies.country",
                verbose_name="Страна",
            ),
        ),
    ]
