# Generated by Django 4.2.6 on 2023-10-13 16:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0002_alter_person_birthdate_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rating",
            name="score",
            field=models.PositiveSmallIntegerField(
                choices=[
                    ("1", 1),
                    ("2", 2),
                    ("3", 3),
                    ("4", 4),
                    ("5", 5),
                    ("6", 6),
                    ("7", 7),
                    ("8", 8),
                    ("9", 9),
                    ("10", 10),
                ],
                verbose_name="Оценка",
            ),
        ),
    ]
