# Generated by Django 4.2.6 on 2023-10-16 13:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0004_alter_person_birthdate_alter_rating_score"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="rating",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
