# Generated by Django 4.2.6 on 2023-10-19 15:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0006_alter_person_birthdate_likedislike"),
    ]

    operations = [
        migrations.AlterField(
            model_name="likedislike",
            name="vote",
            field=models.SmallIntegerField(
                choices=[(1, "нравится"), (-1, "не нравится")],
                null=True,
                verbose_name="Голос",
            ),
        ),
    ]
