# Generated by Django 4.2.6 on 2023-11-07 12:19

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0011_alter_bookmark_managers_alter_person_birthdate_and_more"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="bookmark",
            managers=[],
        ),
        migrations.AlterField(
            model_name="comment",
            name="major",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children",
                to="movies.comment",
                verbose_name="Старший комментарий",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="birthdate",
            field=models.DateField(
                validators=[
                    django.core.validators.MaxValueValidator(
                        datetime.date(2023, 11, 7),
                        "Дата рождения не может быть больше нынешней!",
                    )
                ],
                verbose_name="Дата рождения",
            ),
        ),
    ]
