# Generated by Django 4.2.6 on 2024-03-09 04:24

import datetime
import django.core.validators
from django.db import migrations, models
import movies.fields
import movies.models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0012_alter_bookmark_managers_alter_comment_major_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=movies.fields.WEBPField(blank=True, null=True, upload_to=movies.models.get_image_folder, verbose_name='Постер'),
        ),
        migrations.AlterField(
            model_name='person',
            name='birthdate',
            field=models.DateField(validators=[django.core.validators.MaxValueValidator(datetime.date(2024, 3, 9), 'Дата рождения не может быть больше нынешней!')], verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='person',
            name='picture',
            field=movies.fields.WEBPField(blank=True, null=True, upload_to=movies.models.get_image_folder, verbose_name='Фото'),
        ),
    ]
