# Generated by Django 4.2.6 on 2024-03-10 20:22

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0013_alter_movie_poster_alter_person_birthdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='birthdate',
            field=models.DateField(validators=[django.core.validators.MaxValueValidator(datetime.date(2024, 3, 10), 'Дата рождения не может быть больше нынешней!')], verbose_name='Дата рождения'),
        ),
    ]
